1.3.0
=====

 * Add maximum safe time for a Bot to hold a Sporifier without being confirmed mush
   * Prevent a Sporifier being put down automatically if it is in active use
 * Fix InitialTeam being set to 0 for players/bots logged after Mush selection (meaning all Mush bots would have asterisks in front even if they were never infected in the first place).
 * Fix InitialTeam being ignored when displaying the alignment of a dead Mush in the Scoreboard
 * Make sure that giving the Sporifier on selecting or infecting a Mush doesn't break Weapon/PendingWeapon states
 * Ensure that for any non-PlayerPawn, a Sporifier without ammo is always automatically put down (though this may be redundant)
 * Return from MushMatch.Logout early if the match has already ended
 * Prevent bots from switching to the Sporifier to attack someone if they're already attacking someone else
 * Augment Sporifier's RateSelf when it is solicited by the gametype AI code
 * Penalize for same-team kills, and, by default, multiply any infectee's score by -0.5 (negative of half) to represent reverse contribution to their new team
 * Allow showing score on match end by default
 * Don't notify killing sprees, which can incriminate killers
 * Make the frag reward values for killing or infecting someone, respectively, configurable
