Changelog
=========
Mush Match development team
:homepage: https://github.com/Gustavo6046/MushMatch
:toc:
:numbered:


= 1.3.1

 * Force zero frag limit, and warn if a different value is set in config
 * Fix the majority of settings; there was no way to set those through INI files
 * Have bot attitude always be "ignorant" on match start, never engaging other players
 * Change 'immune-resistance' parameter update and make it also configurable.
 * Slight rebalance to default bot AI suspicion radius values
 * Fix premature ending in network games
 * Fix Beacon firerate setting replication
 * Fix Sporifier being put down for players in netgames
 * Fix tiny-damage AI suspicion culling
 * Make Sporifier not have mush owner spotted if it's in the put down animation

= 1.3.0

 * Add maximum safe time for a Bot to roam around holding a Sporifier when not already a confirmed mush
   * Prevent a Sporifier being put down automatically if it is in active use
 * Fix InitialTeam being set to 0 for players/bots logged after Mush selection (which meant all Mush bots would have asterisks in front even if they were never infected in the first place).
 * Fix InitialTeam being ignored when displaying the alignment of a dead Mush in the Scoreboard
 * Make sure that giving the Sporifier on selecting or infecting a Mush doesn't break Weapon/PendingWeapon states
 * Ensure that for any non-PlayerPawn, a Sporifier without ammo is always automatically put down (though this may be redundant)
 * Return from MushMatch.Logout early if the match has already ended
 * Prevent bots from switching to the Sporifier to attack someone if they're already attacking someone else
 * Augment Sporifier's RateSelf when it is solicited by the gametype AI code
 * Penalize for same-team kills, and, by default, multiply any infectee's score by -0.5 (negative of half) to represent reverse contribution to their new team
 * Allow showing score on match end by default
 * Don't notify killing sprees, which can incriminate killers
 * Make the frag reward values for killing or infecting someone, respectively, configurable
 * Implement (also configurable, and also optional) frag penalties for teamkilling or killing oneself
 * Make every player's underlying team value zero to avoid giving away the team via things like the shield belt energyfield colour or translocator disk light colour
 * Set the default frag limit to zero to prevent sudden match restarts as it is reached; it may still happen if the frag limit is set manually, though
 * Fix respawning upon death when said death is provoked by suicide. Remember, you're only supposed to have one life!
