Todo List
=========
MushMatch Development Team
:toc:
:numbered:

This is the Mush Match todo list. Changes here may be implemented in the
future.

== Wishes

Large plans for the future of MushMatch. Should be fixed within a major version
release.

* Add a **tutorial**, and ingame help e.g. for servers.
** [ ] The tutorial would be for people who install Mush Match into their
game manually (auto-downloads from servers only include the package
with class definitions and assets, and only the map currently on the
server). It would teach all the salient mechanics of the gametype.
(Although I don't have a voice actor ;-;)
** [ ] The in-game help would be helpful when playing Mush Match for the
first time, e.g. auto-downloaded off a server, which would mean being
unable to select it from the singleplayer gametype selection menu later
(which requires the .int file too, which is never auto-downloaded).
It would concisely present some basic info, split into separate topics,
although a primer would be centerpiece for newcomers.

* Add traps that damage (and maybe can spot) mush or help infect humans.
+
Those traps would help make the game more tactically involved.
+
** [ ] There would be two kinds of traps; or rather, the same, but
used differently.
*** [ ] Humans would have access to a trap that sprays _deuterium water_,
which damages mushes and can make it possible to detect them.
*** [ ] Mush would have access to a spore bomb that sprays spore
projectiles outward in the vicinity of a human.

* Add cameras that can suspect players and spot mush.
+
Those cameras would be capable of spotting and suspecting on players; by
below, possibly gradually.
+
** [ ] There would be two kinds of cameras.
+
*** [ ] Turret cameras can only face one direction, but can shoot
suspicion beacons, and can act upon 100% suspicious/spotted
players.
+
*** [ ] Area scanners would rotate at an arc, but would only cause
mushes holding the Sporifier (or doing other distinctly
mushy behaviour) to raise the spotted level, without actually
carrying it out, even were it to reach 100%.
+
** [ ] They could possibly be itemable.
+
Both humans and mush can carry cameras.
+
*** [ ] Both kinds of camera would be able to detect mushiness in the
carrier (if they are mush, of course) and act accordingly.
+
Err, let's just say it's impossible to carry a camera facing away
from oneself.
*
** [ ] They could possibly be damageable.
+
** [ ] Both humans and mush could damage cameras. Destroying them would
render their effect null until a human went up to one (their
presence would automatically progress a 'repair meter').
+
*** [ ] A mush could spend time repairing a camera, and the repaired camera
would operate as sabotaged. But this would be seen as a suspicious act if
any human player were to witness.
+
What a sabotaged camera would do, as opposed to a normal one, is yet to be
decided upon.

* Add meters for suspicion and spotting.
+
As it stands currently, those are instantaneous events.
+
With this idea, however, the Suspicion Meter itself would be affected by
suspicion projectiles, rather than those instantaneously provoke a state of
suspicion upon a player.
+
Suspicion and spotting would not happen, even at 100%, if there was no
human looking (or turret camera; see above).
+
Those meters are ideally separate from the extant 'immune meter', to
disambiguate and allow showing multiple values at once.


== Features

Things that would be nice to implement that aren't as major. Should be fixed
within a minor version release.

_(nil.)_

== Bug Fixes and Technical Stuff

Tiny nuances and peeves. Should be fixed within a patch version release.

_(nil.)_
